//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 餐饮管理.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MY_DIALOG                   102
#define IDR_MAINFRAME                   128
#define IDD_Logindlg                    129
#define IDR_MENU1                       130
#define IDD_kaitaidlg                   132
#define IDD_jiezhangdlg                 135
#define IDD_diancai                     136
#define IDR_TOOLBAR1                    137
#define IDD_jinhuodlg                   139
#define IDD_zhuce                       140
#define IDD_SPinfo                      145
#define IDD_SHULIANG                    146
#define IDD_CPinfo                      147
#define IDD_RSRCX                       149
#define IDD_YSRCX                       150
#define IDD_quanxian                    151
#define IDD_COPY                        152
#define IDD_DIALOG1                     153
#define IDD_DIALOG_retrun               153
#define IDI_ICON_login                  154
#define IDI_ICON_rishouru               156
#define IDI_ICON_reg                    157
#define IDI_ICON_cancel                 158
#define IDI_ICON_pay                    161
#define IDI_ICON_open                   162
#define IDI_ICON_kaitai                 168
#define IDI_ICON_diancai                169
#define IDI_ICON_sl                     178
#define IDD_jiacai                      179
#define IDI_ICON_add                    180
#define IDD_jinhuoselect                181
#define IDB_BITMAP2                     186
#define IDB_BITMAP1                     190
#define IDB_BITMAP3                     191
#define IDD_DIALOG2                     194
#define IDD_EMPLOY                      194
#define IDB_BITMAP4                     196
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_zhaoling               1002
#define IDC_EDIT_pwd1                   1002
#define IDC_zhaoling                    1002
#define IDC_BUTTON_OK                   1003
#define IDC_BUTTON_return               1004
#define IDC_BUTTON_OK2                  1004
#define IDC_ADODC1                      1010
#define IDC_DATAGRID1                   1013
#define IDC_BUTTON_BYE                  1015
#define IDC_EDIT_yingshou               1016
#define IDC_yingshou                    1016
#define IDC_EDIT_shishou                1017
#define IDC_shishou                     1017
#define IDC_COMBO1                      1019
#define IDC_Time                        1030
#define IDC_BUTTON_reset                1032
#define IDC_EDIT_name                   1033
#define IDC_EDIT_pwd                    1034
#define IDC_BUTTON_jinhuo               1038
#define IDC_BUTTON_tuihuo               1039
#define IDC_BUTTON_queding              1040
#define IDC_EDIT_time                   1041
#define IDC_BUTTON_tuichu               1042
#define IDC_EDIT_shuliang               1043
#define IDC_LIST1                       1044
#define IDC_BUTTON_add                  1045
#define IDC_EDIT_price                  1046
#define IDC_EDIT_totle                  1047
#define IDC_LIST_foodlist               1048
#define IDC_LIST_foodbill               1049
#define IDC_LIST2                       1052
#define IDC_LIST3                       1053
#define IDC_BUTTON1                     1054
#define IDC_BUTTON2                     1055
#define IDC_BUTTON                      1056
#define IDC_BUTTON_change               1056
#define IDC_BUTTON_sub                  1057
#define IDC_BUTTON_del                  1057
#define IDC_BUTTON_CANCEL               1058
#define IDC_EDIT_zhuohao                1059
#define IDC_LIST_mingxi                 1060
#define IDC_mingxi                      1060
#define IDC_COMBO_year                  1064
#define IDC_COMBO_month                 1065
#define IDC_COMBO_day                   1066
#define IDC_BUTTON_CHAXUN               1067
#define IDC_RADIO_BOSS                  1068
#define IDC_RADIO_lingban               1069
#define IDC_RADIO_yingyeyuan            1070
#define IDC_BUTTON_CANCLE               1071
#define IDC_BUTTON_checkml              1072
#define IDC_BUTTON3                     1083
#define IDC_BUTTON4                     1084
#define IDC_CHAXUN_BUTTON               1084
#define IDC_TUICHU_BUTTON               1085
#define IDC_EDIT_passwd                 1086
#define IDC_STATIC_CANCEL               1087
#define IDC_EMPLOYEE_LIST               1089
#define IDC_TABLE_USE                   1090
#define IDC_TABLE_UNUSE                 1091
#define IDB_login                       9000
#define IDB_kaitai                      9001
#define IDB_add                         9002
#define IDB_pay                         9003
#define IDB_rishouru                    9004
#define IDB_reg                         9005
#define IDB_cancel                      9006
#define ID_MENU_login                   32771
#define ID_MENU_kaitai                  32775
#define ID_MENU_jiezhang                32776
#define ID_MENU_jiesuan                 32777
#define ID_BUTTON_kaitai                32778
#define ID_BUTTON_jiezhang              32779
#define ID_BUTTON_rishouru              32780
#define ID_MENU_jinhuo                  32781
#define ID_MENU_yuangong                32783
#define ID_BUTTON_zhuce                 32784
#define ID_MENU_about                   32785
#define ID_MENU_SPinfo                  32786
#define ID_MENU_CP                      32787
#define ID_MENU_rishourucx              32789
#define ID_MENU_yueshouricx             32790
#define ID_MENU_sqlcopy                 32791
#define ID_MENU_sqlnew                  32792
#define ID_MENU_quanxian                32793
#define ID_MENU_return                  32794
#define ID_MENU_addcai                  32795
#define ID_MENU_jinhuoselect            32797
#define ID_32798                        32798

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        197
#define _APS_NEXT_COMMAND_VALUE         32799
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
